#!/bin/bash

# This script prints a range of numbers

usage () {
    cat <<END
count [-h] [-r] [-b n] [s n] stop

Print each number up to stop, beginning at 0
   -h show this help message
   -b gives the number to begin with (default: 0)
   -r reverses the count
   -s sets the step size (default: 1 )
END
}

error () {
    echo "Error: $1"
    usage
    exit $2
} >&2

isnum () {
    [[ $1 =~ ^[0-9]+$ ]]
}

# Usage: 

declare reverse=
declare -i begin=0
declare -i step=1

# b: represents whether or not the argument expects a value
# If the whole arg string starts with : it will put getopts in silent mode (won't print anything)
while getopts ":hb:s:r" opt; do
    case $opt in
        r)
            reverse="true"
            ;;
        b)
            isnum ${OPTARG} || error "${OPTARG} is not a number" 1
            start="$OPTARG"
            ;;
        h)  
            usage
            exit 0
            ;;
        s)
            isnum ${OPTARG} || error "${OPTARG} is not a number" 1
            step="$OPTARG"
            ;;
        :)
            error "Option -${OPTARG} is missing an argument" 2
            ;;
        \?)
            error "Uknown option: -${OPTARG}" 3
            ;;
    esac
done

shift $(( OPTIND - 1 ))

[[ $1 ]] || { echo "Missing argument" >&2; exit 1; }
declare end="$1";

if [[ ! $reverse ]]; then
    for (( i=start; i <= end; i += step )); do
        echo $i
    done
else
    for (( i=end; i>= tart; i-= step )); do
        echo $i
    done
fi

exit 0